# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateField()),
                ('author', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('breakwords', models.TextField()),
            ],
        ),
    ]
