# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180913_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='news',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='news',
            name='recommend',
        ),
    ]
