# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180913_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='describe',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='keywords',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='recommend',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
