# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180913_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='describe',
        ),
    ]
